### ISSUE TITLE
[Bug]: Invalid Hook call

### ISSUE THREAD

**Issue by mohamedmehdigara** [reactjs/react.dev#6648]
### Summary

ERROR
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (http://localhost:3000/static/js/bundle.js:33080:17)
    at Object.useContext (http://localhost:3000/static/js/bundle.js:33086:24)
    at useResolvedPath (http://localhost:3000/static/js/bundle.js:30636:42)
    at NavLinkWithRef (http://localhost:3000/static/js/bundle.js:29630:75)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:54627:22)
    at updateForwardRef (http://localhost:3000/static/js/bundle.js:57196:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:59243:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:44223:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:44267:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:44324:35)

### Page

http://localhost:3000/

### Details

https://github.com/mohamedmehdigara/react-interactive-wildlife-platform

**Comment by rickhanlonii** [comment]
Unfortunately, this issue tracker is for reporting bugs in React, and is not a support forum for using React. We want you to find the answer you're looking for, so we suggest posting one of the Community Forums: https://react.dev/community
